name: Build and Publish Container Image

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: web-viewer
      REGISTRY_URL: registry.egi.eu/eureka3d-xr.vo.egi.eu

    steps:
    - uses: actions/checkout@v4
    - name: Prepare environment
      run: |
        IMAGE_TAG=$(date +'%Y-%m-%d_%H%M%S')
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Login to EGI Artefact Registry
      run: |
        echo ${{ secrets.REGISTRY_PASS }} | docker login ${{ env.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USER }} --password-stdin

    - name: Build container image
      run:  |
        docker build \
        -t ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
        -t ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:latest \
        .

    - name: Publish image
      run:  docker push ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Publish image with 'latest' tag
      run: docker push ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:latest
